<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SeerUnityUpdater</RootNamespace>
    <AssemblyName>SeerUnityUpdater</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssetsTools.NET" Version="3.0.5" />
    <PackageReference Include="AssetsTools.NET.Texture" Version="3.0.2" />
    <PackageReference Include="ICSharpCode.Decompiler" Version="11.0.0.9375" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="classdata.tpk" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Seer\YooAsset\" />
  </ItemGroup>

</Project>
